CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_full_name VARCHAR(300) NOT NULL,
    user_email VARCHAR(300) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_email UNIQUE (user_email)

);

CREATE TABLE IF NOT EXISTS items
(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id BIGINT NOT NULL,
    item_name VARCHAR(300) NOT NULL,
    item_description VARCHAR(300) NOT NULL,
    item_availability BOOLEAN NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON UPDATE CASCADE,
    CONSTRAINT item_name_descr_not_blank CHECK (LENGTH(item_name) > 0 AND LENGTH(item_description) > 0)
);

CREATE TABLE IF NOT EXISTS bookings
  (
      booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      item_id BIGINT NOT NULL,
      booker_id BIGINT NOT NULL,
      start_date TIMESTAMP NOT NULL,
      end_date TIMESTAMP NOT NULL,
      booking_status VARCHAR(300) NOT NULL,
      CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items (item_id) ON UPDATE CASCADE,
      CONSTRAINT fk_item_booker FOREIGN KEY (booker_id) REFERENCES users (user_id) ON UPDATE CASCADE
  );

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comment_text VARCHAR(300) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_item_comments FOREIGN KEY (item_id) REFERENCES items (item_id) ON UPDATE CASCADE,
    CONSTRAINT fk_author_owner FOREIGN KEY (author_id) REFERENCES users (user_id) ON UPDATE CASCADE
);